name: build

trigger:
  tags:
    include: ["v*"]
pr: none

pool:
  vmImage: "ubuntu-22.04"

stages:
  - stage: build
    jobs:
      - job: build_package
        displayName: Build Package
        steps:
          - task: UsePythonVersion@0
            displayName: Set python version
            inputs: { versionSpec: 3.11 }
          - script: |
              sudo env "PATH=$PATH" "PIP_USE_PEP517=true" python -m pip install --no-cache-dir -U wheel pip
              python setup.py bdist_wheel
          - publish: $(System.DefaultWorkingDirectory)/dist/
            artifact: dist
          - publish: $(System.DefaultWorkingDirectory)/pipelines/
            artifact: pipelines
          - publish: $(System.DefaultWorkingDirectory)/test/
            artifact: test
  - stage: test
    jobs:
      - job: run_test
        strategy:
          matrix:
            Python3_11:
              python.version: "3.11"
            Python3_12:
              python.version: "3.12"
            Python3_13:
              python.version: "3.13"
        timeoutInMinutes: 10
        steps:
          - checkout: none
          - task: UsePythonVersion@0
            displayName: Set python version
            inputs:
              versionSpec: "$(python.version)"
          - download: current
            artifact: dist
          - download: current
            artifact: pipelines
          - download: current
            artifact: test
          - script: |
              set -x  # Echo commands before they are run
              # Check which version we are building
              export VERSION=${BUILD_SOURCEBRANCH#"refs/tags/v"}
              if [[ "$VERSION" == *dev* ]]; then
                  export TAG=latest
              else
                  export TAG=stable
              fi
              # Start up dependencies ($TAG should pull the respective version of the AL containers)
              sudo docker compose -f test/docker-compose.yml up -d

              # Install configuration & classification file
              sudo mkdir -p /etc/assemblyline/
              sudo cp $(Pipeline.Workspace)/test/config/config.yml /etc/assemblyline/config.yml
              sudo cp $(Pipeline.Workspace)/test/config/classification.yml /etc/assemblyline/classification.yml

              # Install depedency packages
              sudo apt-get update
              sudo apt-get install -y build-essential libffi-dev libfuzzy-dev python3-dev wget

              # Wait for the service containers to come online
              wget https://localhost --no-check-certificate --timeout=2 --retry-on-http-error=502 --waitretry=10 --retry-connrefused
            displayName: Setup Environment
          - script: |
              export VERSION=${BUILD_SOURCEBRANCH#"refs/tags/v"}
              sudo env "PATH=$PATH" "PIP_USE_PEP517=true" python -m pip install -f dist/ "assemblyline-client[test]==${VERSION}"
              sudo env "PATH=$PATH" "PIP_USE_PEP517=true" python -m pip install -r test/requirements.txt
            workingDirectory: $(Pipeline.Workspace)
            displayName: Install assemblyline_client
          - script: |
              set -x  # Echo commands before they are run
              # Check which version we are building
              export VERSION=${BUILD_SOURCEBRANCH#"refs/tags/v"}
              if [[ "$VERSION" == *dev* ]]; then
                  export TAG=latest
              else
                  export TAG=stable
              fi
              export ASSEMBLYLINE_VERSION=$(docker container run --rm cccs/assemblyline-ui:$TAG bash -c 'echo -n "$ASSEMBLYLINE_VERSION"')
              pytest -rsx -vv
            workingDirectory: $(Pipeline.Workspace)/test
            displayName: Test
  - stage: deploy
    jobs:
      - job: deploy
        displayName: Deploy packages and containers
        variables:
          - group: deployment-information
        steps:
          - task: UsePythonVersion@0
            displayName: Set python version
            inputs: { versionSpec: 3.11 }
          - download: current
            artifact: dist
          - script: |
              set -xv  # Echo commands before they are run
              sudo env "PATH=$PATH" "PIP_USE_PEP517=true" python -m pip install --no-cache-dir twine
              ls dist
              twine upload --skip-existing --repository-url $TEST_REPOSITORY_URL dist/*
            displayName: Deploy to Test PyPI
            workingDirectory: $(Pipeline.Workspace)
            env:
              TWINE_USERNAME: $(twineUsername)
              TWINE_PASSWORD: $(twinePasswordTest)
          - script: |
              set -xv  # Echo commands before they are run
              sudo env "PATH=$PATH" "PIP_USE_PEP517=true" python -m pip install --no-cache-dir twine
              ls dist
              twine upload --skip-existing dist/*
            displayName: Deploy to PyPI
            workingDirectory: $(Pipeline.Workspace)
            env:
              TWINE_USERNAME: $(twineUsername)
              TWINE_PASSWORD: $(twinePassword)
