name: tests

trigger: ["*"]
pr: ["*"]

variables:
  - name: "TAG"
    ${{ if eq(variables['System.PullRequest.TargetBranchName'], 'master') }}:
      value: "stable"
    ${{ else }}:
      value: "latest"


schedules:
  - cron: "0 6 * * 1" # Every monday morning
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

pool:
  vmImage: "ubuntu-22.04"

jobs:
  - job: run_test
    strategy:
      matrix:
        Python3_11:
          python.version: "3.11"
        Python3_12:
          python.version: "3.12"
        Python3_13:
          python.version: "3.13"
    timeoutInMinutes: 10
    steps:
      - task: UsePythonVersion@0
        displayName: Set python version
        inputs:
          versionSpec: "$(python.version)"
      - script: |
          set -x  # Echo commands before they are run
          # For debugging, echo the tag we are using to make sure it is correct
          echo $TAG

          # Start up dependencies ($TAG should pull the respective version of the AL containers)
          sudo docker compose -f test/docker-compose.yml up -d

          # Install configuration & classification files
          sudo mkdir -p /etc/assemblyline/
          sudo cp test/config/config.yml /etc/assemblyline/config.yml
          sudo cp test/config/classification.yml /etc/assemblyline/classification.yml

          # Install dependency packages
          sudo apt-get update
          sudo apt-get install -y wget

          # Wait for the service containers to come online
          wget https://localhost --no-check-certificate --timeout=2 --retry-on-http-error=502 --waitretry=10 --retry-connrefused
        displayName: Setup Environment
      - script: |
          sudo env "PATH=$PATH" "PIP_USE_PEP517=true" python -m pip install --pre assemblyline
          sudo env "PATH=$PATH" "PIP_USE_PEP517=true" python -m pip install --no-cache-dir -e . -r test/requirements.txt
        displayName: Install assemblyline_client
      - script: |
          export ASSEMBLYLINE_VERSION=$(docker container run --rm cccs/assemblyline-ui:$TAG bash -c 'echo -n "$ASSEMBLYLINE_VERSION"')
          pytest -rsx -vv
        displayName: Test
